# Generated by Django 5.1.7 on 2025-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtitle', models.CharField(max_length=150)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
