# Generated by Django 5.2 on 2025-05-14 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField()),
                ('dtitle', models.CharField(max_length=150)),
                ('file_path', models.FileField(upload_to='documents/')),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('did', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DocumentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentReviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('review_status', models.CharField(max_length=50)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document', 'submission_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('did', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='submission.document')),
                ('dadviser', models.CharField(max_length=100)),
            ],
        ),
    ]
