# Generated by Django 5.2 on 2025-05-14 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentevaluation',
            name='dauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentevaluation',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.document'),
        ),
        migrations.AddField(
            model_name='documentreviewers',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentreviewers',
            name='did',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.document'),
        ),
        migrations.AddField(
            model_name='documentreviewers',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsubmissionlog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.document'),
        ),
        migrations.AddField(
            model_name='documentsubmissionlog',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='dauthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.program'),
        ),
        migrations.AlterUniqueTogether(
            name='documentreviewers',
            unique_together={('did', 'version', 'reviewer')},
        ),
    ]
